### ISSUE TITLE
1.15 Plugin Compatibility

### ISSUE THREAD

**Issue by jackmawer** [N3FS/issues#13]
Here is a compatibility table demonstrating the progress on plugin support for 1.15:
| Plugin Name | Installed Version | Minecraft Version Supported | 1.15 Ready? |
| --- | --- | --- | --- |
| **CoreProtect** | 2.17.5 | 1.14 | :heavy_check_mark: :up: |
| **WorldEdit** | Build 4843 | 1.14 | :heavy_check_mark: :up: |
| **WorldGuard** | Build 2015 | 1.14 | :heavy_check_mark: :up: |
| **EssentialsX** | 2.17.1.53 | 1.14.4-1.15.2 | :heavy_check_mark: :up: |
| BetterBeds | 0.6.1 | 1.14 | :heavy_check_mark: |
| BungeePortals | 1.3.0 | 1.9 | :warning: |
| CustomDeathMessages | 2.03 | 1.14 | :warning: |
| Citizens2 (Hub Only) | Build 1815 | ? | :warning: :up: |
| Denizen (Hub Only) | Build 1701 | ? | :warning: :up: |
| InventoryRollback(1) | 1.3.6 | 1.14+ | :warning: |
| IronElevators | 1.5 | 1.4.6-1.15 | :heavy_check_mark: |
| LagMeter | 1.17.0 | (?) | :heavy_check_mark: |
| LuckPerms | 5.0.70 | 1.7-1.15 | :heavy_check_mark: |
| LuckPerms-ExtraContexts | Build 12* | 1.7+ | :heavy_check_mark: |
| LWCX | 2.2.2 | 1.13-1.14 | :heavy_check_mark: :up: |
| Maintenance | 3.0.2 | 1.8-1.15(?) | :heavy_check_mark: |
| OpenInv | 4.0.6 | 1.14 | :x: :up: |
| Spark | 1.3.1 | 1.8+ | :heavy_check_mark: |
| Vault | 1.7.1 | 1.13-1.14 | :heavy_check_mark: :up: |

(1) InventoryRollback 1.3.6 supports 1.15, but will output an error to the console on startup. Updating to IR 1.3.7 fixes this.

**Key:**
:heavy_check_mark: Compatible with 1.15
:warning: Needs testing.
:up: An update for this plugin is available.
:x: Not compatible with 1.15, needs replacement.

**Comment by mdcfe** [comment]
* EssentialsX 2.17.1.53 supported 1.14.4, not 1.14.3, and that build also [bumped official 1.15.x support to 1.15.2](https://ci.ender.zone/job/EssentialsX/816). 2.17.2.x is the current version.
* Citizens2's current dev builds include a 1.15 adapter as well as all previous versions, so in theory should work on 1.14.x and 1.15.x.
* According to plugin descriptors (`/version <plugin>`, BungeePortals is at 1.3.0, BetterBeds is at 0.6.1 build 10, CustomDeathMessages is at 2.03.
* Denizen version 1.1.4 claims to support 1.15.2 according to (https://github.com/DenizenScript/Denizen), but no idea how that correlates to Denizen_Developmental builds.
* WE 7.1.0 and WG 7.0.2 added support for 1.15 and we're running dev builds newer than those versions (7.1.1-SNAPSHOT and 7.0.3-SNAPSHOT respectively).
* CustomDeathMessages is version-agnostic, we've used the [same version 2.03](https://dev.bukkit.org/projects/custom-death-messages) since 1.9.

**Comment by jackmawer** [comment]
Updated this list following testing in 1.15. Main issues are InventoryRollback didn't seem to work but didn't produce an error so I can't confirm that, and OpenInv throws an ingame error noting that the version isn't supported.

**Comment by jackmawer** [comment]
Also note that current velocity does not support 1.15, but our velocity plugins seem to work ok on the latest version, so unless you are aware of issues I will update it sometime today.

**Comment by mdcfe** [comment]
For Velocity, we're best sticking to 1.0.6 dev builds until 1.1.0 is stable, since our plugins are built against 1.0.x and the API isn't stable for 1.1.0 yet. 1.0.5 and above support 1.15.2 so that shouldn't be an issue.
